"""Translate airport codes into the ICAO codes the weather API understands.

Airports have two common identifiers:

* **ICAO**, 4 characters, e.g. ``KJFK`` or ``VABB``.  Used by the weather API.
* **IATA**, 3 letters, e.g. ``JFK`` or ``BOM``.  Used on tickets and bags.

The mapping lives in ``data/iata_to_icao.json`` and is generated by
``scripts/update_iata_data.py`` from the Aviation Weather Center station list.
"""

import json
from functools import lru_cache
from pathlib import Path

DATA_FILE = Path(__file__).parent / "data" / "iata_to_icao.json"


@lru_cache(maxsize=1)
def _iata_to_icao() -> dict[str, str]:
    """Load the IATA -> ICAO table once and keep it in memory."""
    with DATA_FILE.open() as f:
        return json.load(f)


def candidate_icao_codes(code: str) -> list[str]:
    """Return the identifiers worth querying the weather API with, best first.

    Args:
        code: An upper-case 3- or 4-character airport code typed by a user.

    A 4-character code is assumed to be ICAO already.  A 3-character code is
    looked up as IATA first; if it is not a known IATA code, ``K`` is
    prepended as a fallback, since US airports with FAA-only identifiers
    (e.g. ``1B9``) use ``K`` + the FAA code as their ICAO code.
    """
    if len(code) == 4:
        return [code]
    candidates = []
    icao = _iata_to_icao().get(code)
    if icao:
        candidates.append(icao)
    if "K" + code not in candidates:
        candidates.append("K" + code)
    return candidates
